DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(
    ID       INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    TRY      DECIMAL,
    USD      DECIMAL,
    EUR      DECIMAL
);

DROP TABLE IF EXISTS HISTORY;

CREATE TABLE HISTORY
(
    ID    INT AUTO_INCREMENT PRIMARY KEY,
    USER  INT          NOT NULL,
    ENTRY VARCHAR(255) NOT NULL,
    FOREIGN KEY (USER) REFERENCES USER (ID)
);

/*INSERT INTO USER(USERNAME, PASSWORD, TRY, USD, EUR)
values ('q', '$2a$10$2ybJGChJ8MefWeoyncJp4.rs1SxcHBaaNPeHgDkToiGgBVMmpy1rG', 20000, 0, 0);*/
